### ISSUE TITLE
Ansible 101のStep2 インベントリーのホスト変数の説明に誤変換

### ISSUE THREAD

**Issue by DonGury0528** [irixjp/katacoda-scenarios#2]
Ansible 101のStep2 インベントリーの説明に誤変換と思われる個所があります。

「ノードに与えるホスト変数 (**複数化**) (ansible_host=xxxx) から構成されます」とありますが、
「ノードに与えるホスト変数 (**複数可**) (ansible_host=xxxx) から構成されます」が正しいように思います。

ご確認よろしくお願いいたします。

**Comment by irixjp** [comment]
ありがとうございます！
修正しておきました！
