### ISSUE TITLE
Problem accessing node-1, node-2 and node-3.

### ISSUE THREAD

**Issue by CatchMeIfYouCan4401** [irixjp/katacoda-scenarios#3]
I can't connect to the remote nodes node-1, node-2 and node-3 in the Ansible playground - https://katacoda.com/irixjp/scenarios/ansible-playground

When I click on the tabs node-1,node-2 and node-3 nothing is shown.

**Comment by irixjp** [comment]
By default, nothing is activated on each node, so it is not accessible.
The node tabs are redirected as follows.

tab:node1 -> host:8081 -> node1:80
tab:node2 -> host:8082 -> node2:80
tab:node3 -> host:8083 -> node3:80

Ex)
`ansible all -b -m yum -a 'name=httpd state=latest'`
`ansible all -b -m service -a 'name=httpd state=started'`

you can access them.
