### ISSUE TITLE
Issue about access apache 

### ISSUE THREAD

**Issue by mirrorcity** [irixjp/katacoda-scenarios#32]
Ansible 101(2.11) Japanese で楽しくStudy しています。ありがとうございます。

> Note: Jupyter 上で演習をしている場合は、アクセスするIPアドレスを ~/inventory_file で確認し、http_access=http://35.73.128.87:8081 に示されたアドレスへブラウザでアクセスしてください。このアドレスは各ノードのポート80へリダイレクトされます。

上記のようにコメントがありますが、 killercoda に移ったタイミングからかコンテナには private address (172.17.0.1-4) がアサインされるようです。よって手元のブラウザからはアクセスできなかったのですが、ansible host に lynx を入れ node-1 の 80 番ポートにアクセスにして動作確認を行いました。

Killercoda でもブラウザから Web ページにアクセスできるようになると嬉しいです。他のシナリオでは `https://ece11834-zzzz-xxxx-yyyy-2311bf0db91b-10-244-7-137-80.papa.r.killercoda.com/` といったURLからアクセスできるようになっているものもあるようです。

**Comment by mirrorcity** [comment]
すみません、本文をよく読めていませんでした。そのすぐ上のリンクをアクセスすればよいだけでした。大変失礼しました。
この Issue は削除いただいて構いません。

**Comment by irixjp** [comment]
ありがとうございます。
また何か見つけたらぜひご報告お願いいたします。
