### ISSUE TITLE
Ansible 103(2.11) Japanese Runtime error : ansible-galaxy collection list

### ISSUE THREAD

**Issue by YutaNonaka** [irixjp/katacoda-scenarios#34]
`ubuntu $ ansible-galaxy collection list
usage: ansible-galaxy collection [-h] COLLECTION_ACTION ...
ansible-galaxy collection: error: argument COLLECTION_ACTION: invalid choice: 'list' (choose from 'init', 'build', 'publish', 'install')`

**Comment by irixjp** [comment]
I could not reproduce that error.

```
(ansible) ubuntu $ ansible-galaxy collection list

# /root/.ansible/collections/ansible_collections
Collection        Version
----------------- -------
community.crypto  1.7.1  
community.docker  3.4.5  
community.general 3.8.0
```

**Comment by YutaNonaka** [comment]
I tried it again and it worked.
Thank you.
