### ISSUE TITLE
演習環境準備コマンドが失敗する

### ISSUE THREAD

**Issue by ito-ham** [irixjp/katacoda-scenarios#35]
主なエラーは下記2件のようです。
**TASK [launch ansible target nodes by container] 失敗**

`failed: [localhost] (item={'name': 'node-1', 'port': 8081}) => {"ansible_loop_var": "item", "changed": false, "item": {"name": "node-1", "port": 8081}, "msg": "Error connecting: Error while fetching server API version: Not supported URL scheme http+docker"}
failed: [localhost] (item={'name': 'node-2', 'port': 8082}) => {"ansible_loop_var": "item", "changed": false, "item": {"name": "node-2", "port": 8082}, "msg": "Error connecting: Error while fetching server API version: Not supported URL scheme http+docker"}
failed: [localhost] (item={'name': 'node-3', 'port': 8083}) => {"ansible_loop_var": "item", "changed": false, "item": {"name": "node-3", "port": 8083}, "msg": "Error connecting: Error while fetching server API version: Not supported URL scheme http+docker"}
`

https://github.com/docker/docker-py/issues/3256
kata_setup.shで指定されるcommunity.dockerのバージョンを3.10.2以降にすることでエラー解消されました。

**community.general インストールエラー**

`ERROR! Unexpected Exception, this is probably a bug: '/api/v3/plugin/ansible/content/published/collections/index/community/general/versions/'
`
https://galaxy.ansible.com/ui/repo/published/community/crypto/?version=1.7.1
>Note: Installing collections with ansible-galaxy is only supported in ansible-core>=2.13.9

kata_setup.shで指定されるansible-coreのバージョンを2.13.9にすることでエラー解消されました。

`ANSIBLE_CORE=2.13.9`
`DOCKER_COLLECTION=3.10.4`

以上、ご確認の程よろしくお願いいたします。

**Comment by irixjp** [comment]
ご報告ありがとうございます！修正を反映いたしました！
