### ISSUE TITLE
Can't ssh into the remote nodes.

### ISSUE THREAD

**Issue by CatchMeIfYouCan4401** [irixjp/katacoda-scenarios#4]
I tried to ssh into the remote nodes using `ssh -i automation-keypair.pem node-1@172.20.0.2` but I was asked `password`, which I didn't knew, can someone help.  
https://katacoda.com/irixjp/scenarios/ansible-playground

**Comment by irixjp** [comment]
The username is incorrect.
Check the ~/inventory file.

`centos` is correct.
