### ISSUE TITLE
コマンド内に不要な ' が付いている模様

### ISSUE THREAD

**Issue by Lab8010** [irixjp/katacoda-scenarios#5]
ご担当者様、お世話になります。
Ansible 101 / Step2 / 演習環境での Ansible の実行において、最初のコマンドに不要な"が付いているように思います。
![image](https://user-images.githubusercontent.com/63944843/89722317-35d3b980-da23-11ea-8fc1-518ece47cc8c.png)

現在のコマンド　cd ~/'
正しいと思われるコマンド　cd ~/

'を外す事で問題なく環境実行が出来ました。
Katacoda及びAnsible経験がないため、当方の理解が正しくない可能性もありますが、ご確認頂けると幸いです。

**Comment by irixjp** [comment]
ありがとうございます。
修正しておきました。

https://github.com/irixjp/katacoda-scenarios/commit/f102736e094262c50c853b2c74505fac41c4ce01
