### ISSUE TITLE
Ansible 101 kata_setup.shが存在しません

### ISSUE THREAD

**Issue by blankey-80** [irixjp/katacoda-scenarios#6]
[root@1f79XXXXXX~]# bash ./kata_setup.sh
bash: ./kata_setup.sh: No such file or directory

**Comment by blankey-80** [comment]
> [root@1f79XXXXXX~]# bash ./kata_setup.sh
> bash: ./kata_setup.sh: No such file or directory

**Comment by irixjp** [comment]
It seems the init process doesn't work in index.json.

https://github.com/irixjp/katacoda-scenarios/blob/master/ansible-101/index.json
https://github.com/irixjp/katacoda-scenarios/blob/master/ansible-102/index.json
https://github.com/irixjp/katacoda-scenarios/blob/master/ansible-103/index.json
https://github.com/irixjp/katacoda-scenarios/blob/master/ansible-104/index.json

I will check it.
